"use client";

import {
  useEffect,
  useMemo,
  useRef,
  useState,
  type MouseEvent as ReactMouseEvent,
} from "react";
import { Link, useRouter } from "@/i18n/navigation";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { NoContent } from "@/components/base/no-content";
import { DEFAULT_PLACEHOLDER_IMAGE } from "@/constants";
import { dateFormat } from "@/helper/date-format";
import { dateManipulation } from "@/helper/date-manipulation";
import { mapEnumPlatform } from "@/helper/map-enum-platform";
import { PlatformEnum } from "@/models/api/knowledge/platform.type";
import {
  useContentAutoGenerateGetSettings,
  useContentSchedulerTimezoneGetTimezone,
} from "@/services/content/content.api";
import {
  useContentOverviewGetCountPosted,
  useContentOverviewGetCountUpcoming,
  useContentOverviewGetUpcoming,
} from "@/services/content/overview";
import { useProductKnowledgeGetAll } from "@/services/knowledge.api";
import {
  addMonths,
  eachDayOfInterval,
  endOfMonth,
  endOfWeek,
  format,
  getDay,
  isBefore,
  isSameDay,
  isSameMonth,
  startOfDay,
  startOfMonth,
  startOfWeek,
  subMonths,
} from "date-fns";
import {
  CalendarClock,
  CalendarDays,
  ChevronLeft,
  ChevronRight,
  FileClock,
  Repeat2,
  Search,
  Sparkles,
  PencilLine,
  WandSparkles,
} from "lucide-react";
import Image from "next/image";
import { useParams, useSearchParams } from "next/navigation";
import { useLocale, useTranslations } from "next-intl";
import { ContentSchedulerUploadDialog } from "./content-scheduler-upload-dialog";
import { TimezoneSelector } from "./timezone-selector";

type SchedulerEvent = {
  id: string;
  title: string;
  date: Date;
  time: string;
  image: string;
  type: "manual" | "repetition";
  platforms: PlatformEnum[];
};

interface ContentSchedulerBoardProps {
  handleIfNoPlatformConnected: () => void;
}

export function ContentSchedulerBoard({
  handleIfNoPlatformConnected,
}: ContentSchedulerBoardProps) {
  const router = useRouter();
  const searchParams = useSearchParams();
  const { businessId } = useParams() as { businessId: string };
  const t = useTranslations("contentScheduler");
  const locale = useLocale();
  const [currentMonth, setCurrentMonth] = useState(() => startOfMonth(new Date()));
  const [selectedDate, setSelectedDate] = useState<Date>(new Date());
  const [searchQuery, setSearchQuery] = useState("");
  const [isUploadDialogOpen, setIsUploadDialogOpen] = useState(false);
  const [showDateActionCard, setShowDateActionCard] = useState(false);
  const [dateActionMenuPosition, setDateActionMenuPosition] = useState<{
    top: number;
    left: number;
  } | null>(null);
  const calendarContainerRef = useRef<HTMLDivElement | null>(null);
  const dateActionMenuRef = useRef<HTMLDivElement | null>(null);

  useEffect(() => {
    const selectedDateQuery = searchParams.get("selectedDate");
    if (!selectedDateQuery) return;

    const parsedDate = new Date(`${selectedDateQuery}T00:00:00`);
    if (Number.isNaN(parsedDate.getTime())) return;

    setSelectedDate(parsedDate);
    setCurrentMonth(startOfMonth(parsedDate));
    setShowDateActionCard(false);
    setDateActionMenuPosition(null);
  }, [searchParams]);

  useEffect(() => {
    if (!showDateActionCard) return;

    const handlePointerDown = (event: PointerEvent) => {
      const target = event.target as Node;

      if (dateActionMenuRef.current?.contains(target)) {
        return;
      }

      if (calendarContainerRef.current?.contains(target)) {
        return;
      }

      setShowDateActionCard(false);
      setDateActionMenuPosition(null);
    };

    document.addEventListener("pointerdown", handlePointerDown);

    return () => {
      document.removeEventListener("pointerdown", handlePointerDown);
    };
  }, [showDateActionCard]);

  const rangeStart = dateManipulation.ymd(startOfMonth(currentMonth));
  const rangeEnd = dateManipulation.ymd(endOfMonth(currentMonth));

  useContentOverviewGetCountUpcoming(businessId, {
    dateStart: rangeStart,
    dateEnd: rangeEnd,
  });
  const { data: postedCountData } = useContentOverviewGetCountPosted(
    businessId,
    {
      dateStart: rangeStart,
      dateEnd: rangeEnd,
    }
  );
  const { data: upcomingData, isLoading } = useContentOverviewGetUpcoming(
    businessId,
    {
      dateStart: rangeStart,
      dateEnd: rangeEnd,
    }
  );
  const { data: autoGenerateData } = useContentAutoGenerateGetSettings(businessId);
  const { data: timezoneData } = useContentSchedulerTimezoneGetTimezone(businessId);
  const { data: productsData } = useProductKnowledgeGetAll(businessId, {
    limit: 100,
    sortBy: "name",
    sort: "asc",
  });

  const productMap = useMemo(() => {
    return new Map(
      (productsData?.data.data || []).map((product) => [product.id, product.name])
    );
  }, [productsData?.data.data]);

  const manualEvents = useMemo<SchedulerEvent[]>(
    () =>
      (upcomingData?.data.data || []).map((item) => ({
        id: `manual-${item.id}`,
        title: item.title || t("scheduledPostLabel"),
        date: new Date(item.date),
        time: dateFormat.getHhMm(new Date(item.date)),
        image: item.images[0] || DEFAULT_PLACEHOLDER_IMAGE,
        type: "manual",
        platforms: item.platforms,
      })),
    [t, upcomingData?.data.data]
  );

  const repetitionEvents = useMemo<SchedulerEvent[]>(() => {
    const settings = autoGenerateData?.data.data;
    if (!settings?.preference?.isActive) {
      return [];
    }

    const datesInMonth = eachDayOfInterval({
      start: startOfMonth(currentMonth),
      end: endOfMonth(currentMonth),
    });

    return settings.schedules.flatMap((daySchedule) =>
      daySchedule.schedules
        .filter((schedule) => schedule.isActive)
        .flatMap((schedule) =>
          datesInMonth
            .filter((date) => getDay(date) === schedule.day)
            .map((date) => ({
              id: `auto-${schedule.id}-${date.toISOString()}`,
              title:
                productMap.get(schedule.productKnowledgeId) ||
                t("contentRepetitionLabel"),
              date: new Date(`${dateManipulation.ymd(date)}T${schedule.time}`),
              time: schedule.time,
              image: DEFAULT_PLACEHOLDER_IMAGE,
              type: "repetition" as const,
              platforms: schedule.platforms,
            }))
        )
    );
  }, [autoGenerateData?.data.data, currentMonth, productMap, t]);

  const mergedEvents = useMemo(
    () =>
      [...manualEvents, ...repetitionEvents].sort(
        (left, right) => left.date.getTime() - right.date.getTime()
      ),
    [manualEvents, repetitionEvents]
  );

  const selectedDateEvents = useMemo(
    () => mergedEvents.filter((item) => isSameDay(item.date, selectedDate)),
    [mergedEvents, selectedDate]
  );

  const filteredEvents = useMemo(() => {
    const source = selectedDateEvents.length > 0 ? selectedDateEvents : mergedEvents;
    const query = searchQuery.trim().toLowerCase();
    if (!query) return source;

    return source.filter((event) => {
      const platformText = event.platforms
        .map((platform) => mapEnumPlatform.getPlatformLabel(platform))
        .join(" ")
        .toLowerCase();

      return (
        event.title.toLowerCase().includes(query) ||
        event.time.toLowerCase().includes(query) ||
        platformText.includes(query)
      );
    });
  }, [mergedEvents, searchQuery, selectedDateEvents]);

  const calendarDays = useMemo(
    () =>
      eachDayOfInterval({
        start: startOfWeek(startOfMonth(currentMonth), { weekStartsOn: 0 }),
        end: endOfWeek(endOfMonth(currentMonth), { weekStartsOn: 0 }),
      }),
    [currentMonth]
  );

  const weekdayLabels = useMemo(() => {
    const baseDate = startOfWeek(new Date(), { weekStartsOn: 0 });
    return eachDayOfInterval({
      start: baseDate,
      end: endOfWeek(baseDate, { weekStartsOn: 0 }),
    }).map((date) =>
      new Intl.DateTimeFormat(locale === "id" ? "id-ID" : "en-US", {
        weekday: "short",
      }).format(date)
    );
  }, [locale]);

  const monthLabel = new Intl.DateTimeFormat(locale === "id" ? "id-ID" : "en-US", {
    month: "long",
    year: "numeric",
  }).format(currentMonth);

  const openDateAction = (
    date: Date,
    event: ReactMouseEvent<HTMLButtonElement>
  ) => {
    if (isBefore(date, startOfDay(new Date()))) {
      return;
    }

    const containerRect = calendarContainerRef.current?.getBoundingClientRect();
    const triggerRect = event.currentTarget.getBoundingClientRect();

    setSelectedDate(date);
    setShowDateActionCard(true);

    if (!containerRect) {
      setDateActionMenuPosition(null);
      return;
    }

    const menuRightEdge = Math.min(
      triggerRect.left -
        containerRect.left +
        triggerRect.width -
        12,
      containerRect.width - 12
    );
    const menuTop = Math.min(
      triggerRect.top - containerRect.top + 8,
      containerRect.height - 116
    );

    setDateActionMenuPosition({
      top: Math.max(menuTop, 12),
      left: Math.max(menuRightEdge, 196),
    });
  };

  const chosenDate = dateManipulation.ymd(selectedDate);

  return (
    <>
      <div className="grid gap-6 lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]">
        <Card>
          <CardContent className="p-4 sm:p-6">
            <div className="mb-4 flex flex-col gap-4 sm:mb-6 sm:flex-row sm:items-center sm:justify-between">
              <div className="flex items-center gap-2 sm:gap-3">
                <h2 className="text-2xl font-bold sm:text-3xl">{monthLabel}</h2>
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => {
                    setCurrentMonth((current) => subMonths(current, 1));
                    setShowDateActionCard(false);
                    setDateActionMenuPosition(null);
                  }}
                >
                  <ChevronLeft className="h-4 w-4" />
                </Button>
                <Button
                  variant="outline"
                  size="icon"
                  onClick={() => {
                    setCurrentMonth((current) => addMonths(current, 1));
                    setShowDateActionCard(false);
                    setDateActionMenuPosition(null);
                  }}
                >
                  <ChevronRight className="h-4 w-4" />
                </Button>
              </div>

              <Button
                variant="outline"
                className="w-full sm:w-auto"
                onClick={() => {
                  setCurrentMonth(startOfMonth(new Date()));
                  setSelectedDate(new Date());
                  setShowDateActionCard(false);
                  setDateActionMenuPosition(null);
                }}
              >
                {t("today")}
              </Button>
            </div>

            <div className="-mx-4 overflow-x-auto px-4 sm:mx-0 sm:px-0">
              <div
                ref={calendarContainerRef}
                className="relative min-w-[720px] overflow-hidden rounded-[24px] border border-border sm:min-w-0 sm:rounded-[28px]"
              >
                <div className="grid grid-cols-7 bg-background-secondary">
                  {weekdayLabels.map((label) => (
                    <div
                      key={label}
                      className="px-2 py-3 text-center text-xs font-medium uppercase tracking-[0.18em] text-muted-foreground sm:px-4 sm:py-4 sm:text-sm sm:tracking-[0.24em]"
                    >
                      {label}
                    </div>
                  ))}
                </div>

                <div className="grid grid-cols-7">
                  {calendarDays.map((day) => {
                    const dayEvents = mergedEvents.filter((item) =>
                      isSameDay(item.date, day)
                    );
                    const isCurrentMonth = isSameMonth(day, currentMonth);
                    const isSelected = isSameDay(day, selectedDate);
                    const isPast = isBefore(day, startOfDay(new Date()));
                    const visibleEvents = dayEvents.slice(0, 3);

                    return (
                      <button
                        key={day.toISOString()}
                        type="button"
                        onClick={(event) => openDateAction(day, event)}
                        className={`flex min-h-[92px] flex-col justify-start border-b border-r px-2 py-2 text-left align-top transition-colors sm:min-h-[116px] sm:px-2.5 sm:py-2.5 xl:min-h-[128px] ${
                          isCurrentMonth ? "bg-card" : "bg-background-secondary/50"
                        } ${isSelected ? "bg-primary/5" : ""} ${
                          isPast ? "cursor-not-allowed opacity-60" : "hover:bg-primary/5"
                        }`}
                      >
                        <div
                          className={`mb-2 text-sm font-semibold sm:mb-3 sm:text-base xl:text-lg ${
                            isCurrentMonth ? "text-foreground" : "text-muted-foreground"
                          }`}
                        >
                          {format(day, "d")}
                        </div>

                        <div className="space-y-1 sm:space-y-1.5">
                          {visibleEvents.map((event) => (
                            <div
                              key={event.id}
                              className={`overflow-hidden rounded-full sm:rounded-lg ${
                                event.type === "manual"
                                  ? "bg-rose-100 text-rose-600"
                                  : "bg-violet-100 text-violet-600"
                              }`}
                            >
                              <div className="h-1.5 sm:hidden" />
                              <div className="hidden px-2 py-1 text-xs leading-tight sm:block">
                                <div className="truncate font-medium">
                                  {event.title}
                                </div>
                                <div className="truncate opacity-90">{event.time}</div>
                              </div>
                            </div>
                          ))}
                          {dayEvents.length > 3 && (
                            <div className="hidden text-[11px] text-muted-foreground sm:block">
                              +{dayEvents.length - 3} {t("more")}
                            </div>
                          )}
                        </div>
                      </button>
                    );
                  })}
                </div>

                {showDateActionCard && dateActionMenuPosition && (
                  <div
                    ref={dateActionMenuRef}
                    className="absolute z-20 w-52 rounded-2xl border border-border bg-card p-2 shadow-[0_18px_40px_rgba(15,23,42,0.18)]"
                    style={{
                      top: dateActionMenuPosition.top,
                      left: dateActionMenuPosition.left,
                      transform: "translateX(-100%)",
                    }}
                  >
                    <button
                      type="button"
                      onClick={() => {
                        setIsUploadDialogOpen(true);
                        setShowDateActionCard(false);
                        setDateActionMenuPosition(null);
                      }}
                      className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-background-secondary"
                    >
                      <span className="flex size-8 items-center justify-center rounded-xl bg-background-secondary text-foreground">
                        <PencilLine className="size-4" />
                      </span>
                      {t("uploadFile")}
                    </button>

                    <button
                      type="button"
                      onClick={() => {
                        setShowDateActionCard(false);
                        setDateActionMenuPosition(null);
                        router.push(
                          `/business/${businessId}/content-generate?scheduleDate=${chosenDate}`
                        );
                      }}
                      className="flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-sm font-medium text-foreground transition-colors hover:bg-background-secondary"
                    >
                      <span className="flex size-8 items-center justify-center rounded-xl bg-primary/10 text-primary">
                        <WandSparkles className="size-4" />
                      </span>
                      {t("buildWithAi")}
                    </button>
                  </div>
                )}
              </div>
            </div>
          </CardContent>
        </Card>

        <div className="space-y-6">
          <Card>
            <CardContent className="p-6 space-y-5">
              <div className="text-2xl font-bold">{t("overview")}</div>

              <div className="grid grid-cols-3 gap-4">
                <div className="flex items-center gap-3 rounded-2xl border border-border px-4 py-3">
                  <div className="rounded-xl bg-rose-100 p-2 text-rose-500">
                    <CalendarClock className="h-4 w-4" />
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">
                      {t("totalScheduled")}
                    </div>
                    <div className="text-xl font-semibold">{mergedEvents.length}</div>
                  </div>
                </div>

                <div className="flex items-center gap-3 rounded-2xl border border-border px-4 py-3">
                  <div className="rounded-xl bg-amber-100 p-2 text-amber-500">
                    <Repeat2 className="h-4 w-4" />
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">
                      {t("contentRepetitionShort")}
                    </div>
                    <div className="text-xl font-semibold">{repetitionEvents.length}</div>
                  </div>
                </div>

                <div className="flex items-center gap-3 rounded-2xl border border-border px-4 py-3">
                  <div className="rounded-xl bg-blue-100 p-2 text-blue-500">
                    <FileClock className="h-4 w-4" />
                  </div>
                  <div>
                    <div className="text-xs text-muted-foreground">
                      {t("postedThisMonth")}
                    </div>
                    <div className="text-xl font-semibold">
                      {postedCountData?.data.data.total || 0}
                    </div>
                  </div>
                </div>
              </div>

              <div className="rounded-2xl border border-border px-4 py-3">
                <TimezoneSelector />
                {timezoneData?.data.data && (
                  <p className="mt-3 text-sm text-muted-foreground">
                    ({timezoneData.data.data.offset}) {timezoneData.data.data.timezone}
                  </p>
                )}
              </div>

              <Link href={`/business/${businessId}/knowledge-base`}>
                <Button className="w-full">
                  <Sparkles className="h-4 w-4" />
                  {t("goToBusinessKnowledge")}
                </Button>
              </Link>
            </CardContent>
          </Card>

          <Card>
            <CardContent className="p-6 space-y-4">
              <div className="flex items-center justify-between gap-4">
                <div>
                  <div className="text-2xl font-bold">{t("scheduledListTitle")}</div>
                  <div className="text-sm text-muted-foreground">
                    {selectedDateEvents.length > 0
                      ? new Intl.DateTimeFormat(
                          locale === "id" ? "id-ID" : "en-US",
                          {
                            weekday: "long",
                            day: "numeric",
                            month: "long",
                          }
                        ).format(selectedDate)
                      : t("showingAllScheduled")}
                  </div>
                </div>
                <div className="text-sm text-muted-foreground">
                  {filteredEvents.length} {t("items")}
                </div>
              </div>

              <div className="relative">
                <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
                <Input
                  value={searchQuery}
                  onChange={(event) => setSearchQuery(event.target.value)}
                  placeholder={t("searchScheduledPlaceholder")}
                  className="pl-10"
                />
              </div>

              <div className="space-y-3">
                {isLoading ? (
                  Array.from({ length: 3 }).map((_, index) => (
                    <div
                      key={index}
                      className="h-24 animate-pulse rounded-2xl bg-background-secondary"
                    />
                  ))
                ) : filteredEvents.length === 0 ? (
                  <NoContent
                    icon={CalendarDays}
                    title={t("noScheduledContent")}
                    titleDescription={t("noScheduledContentDescription")}
                  />
                ) : (
                  filteredEvents.map((event) => (
                    <div
                      key={event.id}
                      className="flex items-center gap-3 rounded-2xl border border-border bg-background-secondary p-3"
                    >
                      <Image
                        src={event.image}
                        alt={event.title}
                        width={56}
                        height={56}
                        className="h-14 w-14 rounded-xl object-cover"
                      />

                      <div className="min-w-0 flex-1">
                        <div className="truncate font-semibold">{event.title}</div>
                        <div className="text-sm text-muted-foreground">
                          {new Intl.DateTimeFormat(
                            locale === "id" ? "id-ID" : "en-US",
                            {
                              weekday: "long",
                              day: "numeric",
                              month: "long",
                              year: "numeric",
                            }
                          ).format(event.date)}{" "}
                          - {event.time}
                        </div>
                        <div className="mt-1 flex flex-wrap gap-1">
                          {event.platforms.map((platform) => (
                            <span
                              key={platform}
                              className={`inline-flex items-center gap-1 rounded-full px-2 py-1 text-xs font-medium ${
                                event.type === "manual"
                                  ? "bg-rose-100 text-rose-600"
                                  : "bg-violet-100 text-violet-600"
                              }`}
                            >
                              {mapEnumPlatform.getPlatformIcon(platform, "h-3 w-3")}
                              {mapEnumPlatform.getPlatformLabel(platform)}
                            </span>
                          ))}
                        </div>
                      </div>

                      <div
                        className={`rounded-full px-3 py-1 text-xs font-semibold ${
                          event.type === "manual"
                            ? "bg-rose-100 text-rose-600"
                            : "bg-violet-100 text-violet-600"
                        }`}
                      >
                        {event.type === "manual"
                          ? t("scheduledBadge")
                          : t("repetitionBadge")}
                      </div>
                    </div>
                  ))
                )}
              </div>
            </CardContent>
          </Card>
        </div>
      </div>

      <ContentSchedulerUploadDialog
        isOpen={isUploadDialogOpen}
        selectedDate={selectedDate}
        onClose={() => setIsUploadDialogOpen(false)}
        onNeedPlatformConnect={handleIfNoPlatformConnected}
        onScheduled={() => setIsUploadDialogOpen(false)}
      />
    </>
  );
}
